name: privado-scan
run-name: Privado privacy scan is running...
on: [push, pull_request]
jobs:
  install_privado:
    runs-on: ubuntu-latest
    container: public.ecr.aws/privado/privado:latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker-practice/actions-setup-docker@1.0.11
      - run: curl -o- https://raw.githubusercontent.com/Privado-Inc/privado-cli/main/install.sh | bash
      - run: ~/.privado/bin/privado scan . --overwrite
